### ISSUE TITLE
Handing am/pm ambiguity

### ISSUE THREAD

**Issue by wachunga** [gethuman/hrsoo#6]
```
"M-F 9-8" should be interpreted as "M-F 9am-8pm"
"M-F 9-9" should be interpreted as "M-F 9am-9pm"
"M-F 9-9" should be interpreted as "M-F 9am-10pm"
```

Currently I'm getting messages like "Start time 900 must be before end time 800".

For cases where am/pm are not provided, I suggest assuming the typical case for business hours which is start time is am and end time is pm.

**Comment by wachunga** [comment]
I could take a shot at these changes if you think this approach makes sense?

**Comment by jeffwhelpley** [comment]
Yeah, that sounds awesome. You are absolutely right that the intention with this library was to do typical business hours use case since within written text people write all sorts of stuff and you can never guarantee it will be in a particular format. If you submit a PR for this I will accept it.
